### ISSUE TITLE
Error 401 "Unauthorized" after epad lite instalation admin user

### ISSUE THREAD

**Issue by dsernahiguita** [RubinLab/epad-dist#26]
Hi,
After the epad-lite installation, it is possible to login in the epad as admin, but it is not possible to execute any action (no create user, not upload files). the error that I see in the development tools is:

<img width="1181" alt="Bildschirmfoto 2020-10-30 um 22 41 29" src="https://user-images.githubusercontent.com/6001712/97759301-0f448c80-1b01-11eb-9aa8-f84f8aafb239.png">

Also in the logs I saw the following errors (it seems that the MariaDB database has not been created):
![Bildschirmfoto 2020-10-30 um 22 44 25](https://user-images.githubusercontent.com/6001712/97759563-93970f80-1b01-11eb-8688-900e7f6a4984.png)

![Bildschirmfoto 2020-10-30 um 22 50 41](https://user-images.githubusercontent.com/6001712/97759954-6303a580-1b02-11eb-9cde-5f31a0bcc20b.png)

Below you can see the docker-compose that we are using:
version: "3"
services:
  myepadjs:
    build: ./epadjs
    container_name: epad_js
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./epadjs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./epadjs/entrypoint.sh:/usr/local/bin/entrypoint
    environment:
      REACT_APP_AUTH_URL: "http://25.2.163.181/keycloak/auth"
      PUBLIC_URL: "http://25.2.163.181"
      REACT_APP_API_URL: "http://25.2.163.181/api"
      REACT_APP_WADO_URL: "wadouri:http://25.2.163.181/api/wado"
      REACT_APP_BASE_URL: ""
      REACT_APP_AUTH_MODE: ""
      REACT_APP_MODE: "lite"
    depends_on:
      - myepadlite
    networks:
      - epad-network
  mykeycloak:
    build: ./keycloak
    container_name: epad_keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=vivamed123
      - DB_VENDOR=H2
      - PROXY_ADDRESS_FORWARDING=true
    # expose:
    #   - "8899"
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json,/opt/jboss/keycloak/realm-export_epad.json"
    # ports:
    #   - "8899:8080"
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/realm-export.json
      - ./realm-export_epad.json:/opt/jboss/keycloak/realm-export_epad.json
      - ./terms.ftl:/opt/jboss/keycloak/themes/base/login/terms.ftl
      - ../tmp:/tmp
    depends_on:
      - mycouchdb
    networks:
      - epad-network
  mycouchdb:
    image: ibmcom/couchdb3:latest
    container_name: epad_couchdb
    # expose:
    #   - "8888"
    # ports:
    #   - "8888:5984"
    volumes:
      - "../couchdbloc:/opt/couchdb/data"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=vivamed123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 1m30s
      timeout: 1m
      retries: 10
    depends_on:
      - mymariadb
    networks:
      - epad-network
  mymariadb:
    image: rubinlab/mariadb:latest
    container_name: epad_mariadb
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=admin --password=vivamed --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    # expose:
    #   - "3306"
    # ports:
    #   - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ../mariadbloc:/var/lib/mysql
      - ./epaddb_nodata.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: epaddb
      MYSQL_USER: admin
      MYSQL_PASSWORD: vivamed
      MYSQL_ROOT_PASSWORD: rootvivamed
    networks:
      - epad-network
  mydicomweb:
    build: ./dicomweb-server
    container_name: epad_dicomweb
    # expose:
    #   - "8090"
    # ports:
    #   - "8090:8090"
    environment:
      DB_SERVER: "http://admin:vivamed123@epad_couchdb"
      DB_NAME: "chronicle"
      AUTH: "none"
      LOGGER: "true"
      PREFIX: "/pacs"
    depends_on:
      - mykeycloak
    healthcheck:
      test: ["CMD", "pm2", "show", "DICOMwebServer"]
      interval: 1m30s
      timeout: 1m
      retries: 10
    networks:
      - epad-network
  myepadlite:
    container_name: epad_lite
    build:
     context: ./epadlite
     dockerfile: Dockerfile
     args:
       ARG_EPAD_DOCKER_GID: 999
    # expose:
    #   - "8080"
    # ports:
    #   - "8080:8080"
    environment:
      NOSQL_DB_HOST: "http://admin:vivamed123@epad_couchdb"
      NOSQL_DB_NAME: "epadlite"
      LOGGER: "true"
      HTTPS: "false"
      MODE: "lite"
      PREFIX: "api"
      SQL_DB_HOST: "epad_mariadb"
      SQL_DB_NAME: "epaddb"
      SQL_USER: "admin"
      SQL_PASS: "vivamed"
      SQL_LOGGER: "false"
      AUTH_URL: "http://25.2.163.181/keycloak"
      DICOMWEB_BASEURL: "http://epad_dicomweb:8090/pacs"
      AUTH: "auth"
      AUTH_USERINFO_URL: "{epadlite_authuserinfourl}"
    volumes:
      - ../data:/home/node/app/data
      - ../pluginData:/home/node/app/pluginsDataFolder
      -  /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mydicomweb
    healthcheck:
      test: ["CMD", "pm2", "show", "ePADlite"]
      interval: 1m30s
      timeout: 1m
      retries: 10
    networks:
      - epad-network
networks:
  epad-network:
    driver: bridge

Epad.yml file used by the installation:
host: 25.2.163.181
mode: lite
config: environment
cache: 
  size: "10g"
  inactivetime: "60m"
compression:
  minsize: "20"
keycloak:
  mode: build
  dockerfiledir: ".\/keycloak"
  user: admin
  password: vivamed123
  email: vivamed@eafit.edu
  port: 8899
  loc: "keycloak"
couchdb:
  mode: image
  image: "ibmcom\/couchdb3:latest"
  user: admin
  password: vivamed123
  port: 8888
  dblocation: "..\/couchdbloc" 
dicomweb:
  mode: build
  dockerfiledir: ".\/dicomweb-server"
  port: 8090
  dbname: chronicle
  log: true
  auth: none
  loc: "pacs"
  branch: "master" 
epadlite:
  mode: build
  dockerfiledir: ".\/epadlite"
  port: 8080
  dbname: epadlite
  log: true
  https: false
  auth: auth
  loc: "api"
  branch: "master"
epadjs:
  mode: build
  dockerfiledir: ".\/epadjs"
  port: 80
  branch: "master"
mariadb:
  mode: image
  image: latest
  dbname: epaddb
  user: admin
  password: vivamed
  rootpassword: rootvivamed
  port: 3306
  log: false
  backuploc: ".\/epaddb_nodata.sql"
  dblocation: "..\/mariadbloc" 

Thanks in advance
Diana Lucia Serna Higuita

**Comment by acavit** [comment]
Hi Diana. Are you using mac or linux ? Did you use installation script ? 
If you used installation script,  did you have a previously installed mariadb at ../mariadbloc folder path? For now installation script does not delete the database data. 
Possible issues :
You have a previously installed mariadb and it has different password than the password that you provided during the new installation.
   If this is the case and If you want to keep your data we will need to change your passwords for your mariadb. If the database is still empty please delete the mariadb data folder which is "" and reinstall ePad.
  If this is not the case and if you are freshly installed everything please follow the steps below to double check your mariadb users and paswords. 

Let me know how it goes please.
Thanks

Would you double check if you can use your passwords with mariadb in mariadb container? 
To check your mariadb passwords:
1. open a terminal in your container:
    docker exec -it epad_mariadb sh
2 login to your mariadb 
   mysql -uroot -p 
3 After the previous mysql command it will ask you your password for mariadb root user and it should be rootvivamed (form what you have provided)
4. if the section 3 works please repeat the steps 2 for the user admin with the password vivamed . Please terminate previous mysql session by typing " exit; " and enter. After terminating mysql session you will be ready to repeat section 2 as directed above.

**Comment by acavit** [comment]
Another suggestion. Would you check your epad.yml file in epad-dist and would you verify that the mariadb users and passwords are the same in both files. In the docker-compose.yml file and in the epad.yml file.
Thanks

**Comment by dsernahiguita** [comment]
Hi acavit,

thanks a lot for you answer!
I am using linux Debian and the epad.yml file to make the installation.

Unfortunately after several attempts still I have the same issue :(.
I followed the steps:

1. I compared both files epad.yml and docker-compose and the mariadb users and password are the same in both files.
2. I tried to connect the database mariadb using the user and password defined into the epad.yml 
but I get the following error:

![Bildschirmfoto 2020-11-03 um 22 10 47](https://user-images.githubusercontent.com/6001712/98040934-7031d480-1e21-11eb-9c67-7cb2aa41d39d.png)

**but if I let the password empty it was possible to connect with the database using the users root and admin**

3. To be sure I had uninstalled the application by using docker-compose down, also I had checked that all the epad containers were deleted and I deleted all the folders.
 
4. I had downloaded the epad-dist last release, changed the values in the epad.yml, for the mariadb user, password and root password I had used admin, admin
5. I had installed the application but still I got the same problem
6. I tried to connect the database mariadb using the user and password defined into the epad.yml (admin admin) but still it was not possible to connect with mariadb.
**7. I tried to connect the database mariadb using the user admin and root and empty password and it was possible to connect ito the database**

could you please check why it is possible to connect to the mariadb database without a password  even though the passwords are defined into the epad.yml and docker-compose.yml

below you can find the epad.yml and docker-compose.yml

Epad.yml:
host: 25.2.163.181
mode: lite
config: environment
cache: 
  size: "10g"
  inactivetime: "60m"
compression:
  minsize: "20"
keycloak:
  mode: build
  dockerfiledir: ".\/keycloak"
  user: admin
  password: vivamed123
  email: vivamed@eafit.edu.co
  port: 8899
  loc: "keycloak"
couchdb:
  mode: image
  image: "2.3.1"
  user: admin
  password: admin
  port: 8888
  dblocation: "..\/couchdbloc" 
dicomweb:
  mode: build
  dockerfiledir: ".\/dicomweb-server"
  port: 8090
  dbname: chronicle
  log: true
  auth: none
  loc: "pacs"
  branch: "master" 
epadlite:
  mode: build
  dockerfiledir: ".\/epadlite"
  port: 8080
  dbname: epadlite
  log: true
  https: false
  auth: auth
  loc: "api"
  branch: "master"
epadjs:
  mode: build
  dockerfiledir: ".\/epadjs"
  port: 80
  branch: "master"
mariadb:
  mode: image
  image: latest
  dbname: epaddb
  user: admin
  password: admin
  rootpassword: admin
  port: 3306
  log: false
  backuploc: ".\/epaddb_nodata.sql"
  dblocation: "..\/mariadbloc" 


docker-compose.yml
version: "3"
services:
  myepadjs:
    build: ./epadjs
    container_name: epad_js
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./epadjs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./epadjs/entrypoint.sh:/usr/local/bin/entrypoint
    environment:
      REACT_APP_AUTH_URL: "http://25.2.163.181/keycloak/auth"
      PUBLIC_URL: "http://25.2.163.181"
      REACT_APP_API_URL: "http://25.2.163.181/api"
      REACT_APP_WADO_URL: "wadouri:http://25.2.163.181/api/wado"
      REACT_APP_BASE_URL: ""
      REACT_APP_AUTH_MODE: ""
      REACT_APP_MODE: "lite"
    depends_on:
      - myepadlite
    networks:
      - epad-network
  mykeycloak:
    build: ./keycloak
    container_name: epad_keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=vivamed123
      - DB_VENDOR=H2
      - PROXY_ADDRESS_FORWARDING=true
    # expose:
    #   - "8899"
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json,/opt/jboss/keycloak/realm-export_epad.json"
    # ports:
    #   - "8899:8080"
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/realm-export.json
      - ./realm-export_epad.json:/opt/jboss/keycloak/realm-export_epad.json
      - ./terms.ftl:/opt/jboss/keycloak/themes/base/login/terms.ftl
      - ../tmp:/tmp
    depends_on:
      - mycouchdb
    networks:
      - epad-network
  mycouchdb:
    image: apache/couchdb:2.3.1
    container_name: epad_couchdb
    # expose:
    #   - "8888"
    # ports:
    #   - "8888:5984"
    volumes:
      - "../couchdbloc:/opt/couchdb/data"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 1m30s
      timeout: 1m
      retries: 10
    depends_on:
      - mymariadb
    networks:
      - epad-network
  mymariadb:
    image: rubinlab/mariadb:latest
    container_name: epad_mariadb
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=admin --password=admin --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    # expose:
    #   - "3306"
    # ports:
    #   - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ../mariadbloc:/var/lib/mysql
      - ./epaddb_nodata.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: epaddb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - epad-network
  mydicomweb:
    build: ./dicomweb-server
    container_name: epad_dicomweb
    # expose:
    #   - "8090"
    # ports:
    #   - "8090:8090"
    environment:
      DB_SERVER: "http://admin:admin@epad_couchdb"
      DB_NAME: "chronicle"
      AUTH: "none"
      LOGGER: "true"
      PREFIX: "/pacs"
    depends_on:
      - mykeycloak
    healthcheck:
      test: ["CMD", "pm2", "show", "DICOMwebServer"]
      interval: 1m30s
      timeout: 1m
      retries: 10
    networks:
      - epad-network
  myepadlite:
    container_name: epad_lite
    build:
     context: ./epadlite
     dockerfile: Dockerfile
     args:
       ARG_EPAD_DOCKER_GID: 999
    # expose:
    #   - "8080"
    # ports:
    #   - "8080:8080"
    environment:
      NOSQL_DB_HOST: "http://admin:admin@epad_couchdb"
      NOSQL_DB_NAME: "epadlite"
      LOGGER: "true"
      HTTPS: "false"
      MODE: "lite"
      PREFIX: "api"
      SQL_DB_HOST: "epad_mariadb"
      SQL_DB_NAME: "epaddb"
      SQL_USER: "admin"
      SQL_PASS: "admin"
      SQL_LOGGER: "false"
      AUTH_URL: "http://25.2.163.181/keycloak"
      DICOMWEB_BASEURL: "http://epad_dicomweb:8090/pacs"
      AUTH: "auth"
      AUTH_USERINFO_URL: "{epadlite_authuserinfourl}"
    volumes:
      - ../data:/home/node/app/data
      - ../pluginData:/home/node/app/pluginsDataFolder
      -  /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mydicomweb
    healthcheck:
      test: ["CMD", "pm2", "show", "ePADlite"]
      interval: 1m30s
      timeout: 1m
      retries: 10
    networks:
      - epad-network
networks:
  epad-network:
    driver: bridge

Thanks in advance
Diana

**Comment by acavit** [comment]
Hi Diana , I have tested on Centos7 and macos and I couldn't reproduce empty password issue. I am setting a testing environment for Debian to double check. 

- First option can be is to delete mariadb data (looks like your data is in ../mariadbloc . If you have crucial data don't use first option and continue with the second option )and stop and delete epad_mariadb container :
docker stop epad_mariadb
docker rm epad_mariadb 

And then delete epad_mariadb image 
docker images (this will list images. You need image id or repo name )
docker rmi imageidOrimagerepository (this will delete the image)
After the steps above you can recall docker-compose up -d (you need to switch to the directory where you have docker-comopse.yml file)
Now you should have fresh ePad database with the correct password.

- Second option:
You may want to update manually mariadb password in the epad_mariadb container according to the credentials which you have in docker-compose.yml file to see if you have further issues. By the way you are using the lite version of ePad. If you need project , user management etc. you should use thick version. (mode: thick). 

To update mariadb passwords in container:
docker exec -it epad_mariadb sh
mysql -uroot -p
use mysql;

here double check you users in mariadb : 
select Host,User from user;

you should see 
admin
root
root

If you see something else let me know please.
If you see as listed above, proceed with the following commands to update the passwords.
ALTER USER 'root'@'localhost' IDENTIFIED BY ‘passwordindockercompose’;
ALTER USER 'admin'@'%' IDENTIFIED BY ‘passwordindockercompose’;

Remember, these changes are made in container and if you do docker-compose down (means we delete containers) All the password changes that you have done in container will be reset. Instead of docker-compose down please use:
docker stop containername
docker start containername  
to keep password changes.

Another suggestion:
If you have no data and if this is the first time that you are installing ePad please delete folders container and images related to ePad

to remove containers:
docker-compose down

and delete ePad images.

to list images: (you will need the imageid or the repository of the image to delete)
docker images

to delete an image 
docker rmi idoftheimageORtherepositoryoftheimage

 and download installation script (epad.stanford.edu, under downloads)and make a fresh installation. Still I would like to investigate to understand the cause if we can have a remote connection if your setup permits.

Let me know please. 
Cavit Altindag
email: cavitaltindag@gmail.com

**Comment by acavit** [comment]
Hi Diana . One more detail when you edit the passwords in the epad.yml file do you rebuild epad_lite_dist folder by using ./configure_epad.sh ../epad_lite_dist ./epad.yml ? If you don't build epad_lite_dist after each epad.yml edit , these changes will not reflect to your epad_lite_dist folder. 
For example : 
I edit epad.yml with the new paswords and after that I go and edit docker-compose.yml in epad_lite_dist and then i use docker-compose up -d to start ePad. This example shows a wrong way to edit files.

**Comment by waybarrios** [comment]
@acavit @dsernahiguita looping on this issue, I re-do everything mention above but I got this one. 


```
epad_lite     | {"level":40,"time":1605725902055,"pid":17,"hostname":"314a30893b7f","msg":"Waiting for mariadb server. Connecting to mariadb epaddb. Error: (conn=-1, no: 1130, SQLState: HY000) Host '172.20.0.6' is not allowed to connect to this MariaDB server","v":1}
epad_lite     | warning: please use IANA standard timezone format ('Etc/GMT0')
epad_lite     | {"level":40,"time":1605725905065,"pid":17,"hostname":"314a30893b7f","msg":"Waiting for mariadb server. Connecting to mariadb epaddb. Error: (conn=-1, no: 1130, SQLState: HY000) Host '172.20.0.6' is not allowed to connect to this MariaDB server","v":1}
epad_lite     | warning: please use IANA standard timezone format ('Etc/GMT0')
epad_lite     | {"level":40,"time":1605725908073,"pid":17,"hostname":"314a30893b7f","msg":"Waiting for mariadb server. Connecting to mariadb epaddb. Error: (conn=-1, no: 1130, SQLState: HY000) Host '172.20.0.6' is not allowed to connect to this MariaDB server","v":1}
epad_lite     | warning: please use IANA standard timezone format ('Etc/GMT0')
epad_lite     | {"level":40,"time":1605725911083,"pid":17,"hostname":"314a30893b7f","msg":"Waiting for mariadb server. Connecting to mariadb epaddb. Error: (conn=-1, no: 1130, SQLState: HY000) Host '172.20.0.6' is not allowed to connect to this MariaDB server","v":1}

```

**Comment by acavit** [comment]
Hi Wayner. Would you send me a screenshot or would you tell me about all
ePad containers status please (to do : docker ps -a ). You will see healthy
, starting or unhealthy.
Thanks

**Comment by thomasjtaylor** [comment]
I am experiencing some of the same issues as @waybarrios on Ubuntu 20.04 with 16GB RAM.

I used the latest (2021-11-03) `epad_manage.sh install` script to configure my instance. 

First, I had to fix a problem in the `production_epadlite.js` which prevented the epad_lite container from starting  [PR-47](https://github.com/RubinLab/epad-dist/pull/47).

### 1. epad_lite | epad_mariadb Access denied for user [fixed, manully]
Next, I found the following entries in the epad_lite and epad_mariadb logs.

```
epad_lite     | {"level":40,"time":1635889493993,"pid":18,"hostname":"e324032eae4d","msg":"Waiting for mariadb server. Connecting to mariadb epaddb. Error: (conn=-1, no: 1130, SQLState: HY000) Host '172.28.0.6' is not allowed to connect to this MariaDB server"}
...
epad_mariadb  | 2021-11-02 21:44:54 32 [Warning] Access denied for user 'admin'@'localhost' (using password: YES)
epad_mariadb  | 2021-11-02 21:44:56 33 [Warning] Aborted connection 33 to db: 'unconnected' user: 'unauthenticated' host: '172.28.0.6' (This connection closed normally without authentication)
```
I was able to fix this by creating the `'admin'@'localhost'` user in mariadb:
```
sudo docker exec -it epad_mariadb bash
root@9e218bbd6a1f:/# mysql
MariaDB [(none)]> use mysql;
MariaDB [mysql]> CREATE USER 'admin'@'localhost' IDENTIFIED BY 'EPAD_MARIADB_PASSWORD';
MariaDB [mysql]> GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost';
MariaDB [mysql]> FLUSH PRIVILEGES;
```
Could it be that the custom mariadb Docker image overrides the `entrypoint.sh` script and ignores the `MYSQL_PASSWORD` environment variables?

### 2. epad_couchbd _users does not exist [fixed, manually]
Next, I found a problem in the epad_couchdb log
```
epad_couchdb  | [error] 2021-11-02T21:43:39.608713Z couchdb@127.0.0.1 emulator -------- Error in process <0.845.0> on node 'couchdb@127.0.0.1' with exit value:
epad_couchdb  | {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,403}]},{mem3_shards,for_docid,3,[{file,"src/mem3
```
This was fixed by creating the `_users` database in epad_couchdb
```
 sudo docker exec -it epad_couchdb bash
bash-4.4$ curl -X GET http://admin:EPAD_COUCHDB_PASSWORD@localhost:5984/_all_dbs
["chronicle","epadlite"]
bash-4.4$ curl -X PUT http://admin:EPAD_COUCHDB_PASSWORD@localhost:5984/_users
{"ok":true}
bash-4.4$ curl -X GET http://admin:EPAD_COUCHDB_PASSWORD@localhost:5984/_all_dbs
["_users","chronicle","epadlite"]
```

### 3. epad_lite | epad_mariadb Host is not allowed to connect to this MariaDB Server [fixed, manually]

This could be similar to (1) (MariaDB user unauthorized). Instead of `'admin'@'localhost'` the user may need to be changed to `'admin'@'%'` or `'admin'@'172.28.0.6'`.
```
epad_lite     | {"level":40,"time":1635952002510,"pid":18,"hostname":"e324032eae4d","msg":"Waiting for mariadb server. Connecting to mariadb epaddb. Error: (conn=-1, no: 1130, SQLState: HY000) Host '172.28.0.6' is not allowed to connect to this MariaDB server"}
epad_mariadb  | 2021-11-03 15:06:45 40808 [Warning] Aborted connection 40808 to db: 'unconnected' user: 'unauthenticated' host: '172.28.0.6' (This connection closed normally without authentication)
```
I was able to fix this by creating the `'admin'@'%'` user in mariadb:
```
sudo docker exec -it epad_mariadb bash
root@9e218bbd6a1f:/# mysql
MariaDB [(none)]> use mysql;
MariaDB [mysql]> CREATE USER 'admin'@'%' IDENTIFIED BY 'EPAD_MARIADB_PASSWORD';
MariaDB [mysql]> GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';
MariaDB [mysql]> FLUSH PRIVILEGES;
```

### 4. Chrome Error: Request failed with status code 401: /api/users/admin 401 (Unauthorized) [Fixed by (3) above)

The ePAD Web UI opens and prompts for the ePAD username and password. When I enter the wrong password, it shows an error message and keeps the login dialog open. When I enter the correct password, the login dialog disappears and the following error messages are in the Chrome console log.

```
Navigated to http://ohio/
keycloak.js:804 [KEYCLOAK] Estimated time difference between browser and server is 1 seconds
xhr.js:177 GET http://ohio/api/users/admin 401 (Unauthorized)
...
httpService.js:35 Error: Request failed with status code 401
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.h.onreadystatechange (xhr.js:62)
App.js:864 Error: Request failed with status code 401
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.h.onreadystatechange (xhr.js:62)
```

### 5. Chrome Error: Service Unavailable (503)  /api/users/admin

After fixing the MariaDB user permissions (1, 3 above), the 401 Unauthorized (4 above) is replaced with a 503 Service Unavailable error.

Chrome Console:
```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)   /api/users/admin
```
ePAD Logs:
```
epad_js       | 172.29.0.1 - - [03/Nov/2021:20:54:38 +0000] "GET /login HTTP/1.1" 200 1145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
epad_js       | 172.29.0.1 - - [03/Nov/2021:20:54:38 +0000] "GET /static/js/2.b1782614.chunk.js HTTP/1.1" 304 0 "http://ohio/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
epad_js       | 172.29.0.1 - - [03/Nov/2021:20:54:38 +0000] "GET /static/js/main.eb256699.chunk.js HTTP/1.1" 304 0 "http://ohio/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
epad_js       | 172.29.0.1 - - [03/Nov/2021:20:54:39 +0000] "GET /keycloak/auth/realms/ePad/protocol/openid-connect/auth?client_id=epad-auth&redirect_uri=http%3A%2F%2Fohio%2Flogin&state=4f00af02-4a54-445d-bd33-8374a26d88a9&response_mode=fragment&response_type=code&scope=openid&nonce=d2ded296-90f5-4cbb-af0d-87d50508dad4 HTTP/1.1" 302 0 "http://ohio/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
epad_js       | 172.29.0.1 - - [03/Nov/2021:20:54:39 +0000] "GET /keycloak/auth/realms/ePad/protocol/openid-connect/login-status-iframe.html HTTP/1.1" 200 1398 "http://ohio/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
epad_js       | 172.29.0.1 - - [03/Nov/2021:20:54:39 +0000] "POST /keycloak/auth/realms/ePad/protocol/openid-connect/token HTTP/1.1" 200 4156 "http://ohio/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
epad_js       | 172.29.0.1 - - [03/Nov/2021:20:54:39 +0000] "GET /keycloak/auth/realms/ePad/protocol/openid-connect/userinfo HTTP/1.1" 200 194 "http://ohio/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
epad_js       | 172.29.0.1 - - [03/Nov/2021:20:54:39 +0000] "GET /keycloak/auth/realms/ePad/protocol/openid-connect/login-status-iframe.html/init?client_id=epad-auth&origin=http%3A%2F%2Fohio HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
epad_js       | 172.29.0.1 - - [03/Nov/2021:20:54:39 +0000] "GET /api/users/admin HTTP/1.1" 503 80 "http://ohio/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
```

The corresponding Docker container logs shows that epad_lite records an `UnauthenticatedError getaddrinfo ENOTFOUND hostname`
```
epad_js       | 172.28.0.1 - - [03/Nov/2021:15:07:04 +0000] "POST /keycloak/auth/realms/ePad/protocol/openid-connect/token HTTP/1.1" 200 4156 "http://ohio/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
epad_js       | 172.28.0.1 - - [03/Nov/2021:15:07:04 +0000] "GET /keycloak/auth/realms/ePad/protocol/openid-connect/userinfo HTTP/1.1" 200 194 "http://ohio/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
epad_js       | 172.28.0.1 - - [03/Nov/2021:15:07:04 +0000] "GET /keycloak/auth/realms/ePad/protocol/openid-connect/login-status-iframe.html/init?client_id=epad-auth&origin=http%3A%2F%2Fohio HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
epad_lite     | {"level":30,"time":1635952024408,"pid":18,"hostname":"e324032eae4d","reqId":"req-e","req":{"method":"GET","url":"/api/users/admin","hostname":"ohio","remoteAddress":"172.28.0.7","remotePort":55268},"msg":"incoming request"}
epad_lite     | {"level":50,"time":1635952024430,"pid":18,"hostname":"e324032eae4d","reqId":"req-e","req":{"method":"GET","url":"/api/users/admin","hostname":"ohio","remoteAddress":"172.28.0.7","remotePort":55268},"res":{"statusCode":500},"err":{"type":"UnauthenticatedError","message":"Verifying token and getting userinfo: getaddrinfo ENOTFOUND ohio","stack":"UnauthenticatedError: Verifying token and getting userinfo: getaddrinfo ENOTFOUND ohio\n    at Object.authCheck (/home/node/app/plugins/Other.js:1524:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.auth (/home/node/app/plugins/Other.js:1700:26)","name":"UnauthenticatedError","data":{"message":"Verifying token and getting userinfo: getaddrinfo ENOTFOUND ohio"}},"msg":"Verifying token and getting userinfo: getaddrinfo ENOTFOUND ohio"}
epad_lite     | {"level":50,"time":1635952024431,"pid":18,"hostname":"e324032eae4d","msg":"Cannot notify user Cannot read properties of undefined (reading 'username')"}
epad_js       | 172.28.0.1 - - [03/Nov/2021:15:07:04 +0000] "GET /api/users/admin HTTP/1.1" 401 118 "http://ohio/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
epad_lite     | {"level":30,"time":1635952024440,"pid":18,"hostname":"e324032eae4d","reqId":"req-e","res":{"statusCode":401},"responseTime":31.45209999382496,"msg":"request completed"}
```

### Docker Container Status
```
docker ps -a | grep epad
ec360b146de5   epad_lite_dist_myepadjs                                    "entrypoint nginx -g…"   17 hours ago   Up 17 hours                 0.0.0.0:80->80/tcp, :::80->80/tcp                      epad_js
e324032eae4d   epad_lite_dist_myepadlite                                  "docker-entrypoint.s…"   17 hours ago   Up 17 hours (healthy)       8080/tcp                                               epad_lite
eb574466c707   epad_lite_dist_mydicomweb                                  "docker-entrypoint.s…"   17 hours ago   Up 17 hours (healthy)       0.0.0.0:4002->4002/tcp, :::4002->4002/tcp, 8090/tcp    epad_dicomweb
f0a24001e2e5   epad_lite_dist_mykeycloak                                  "/opt/jboss/tools/do…"   17 hours ago   Up 17 hours                 8080/tcp, 8443/tcp                                     epad_keycloak
0728bd8a43d7   ibmcom/couchdb3:latest                                     "/docker-entrypoint.…"   17 hours ago   Up 17 hours (healthy)       4369/tcp, 5984/tcp, 9100/tcp                           epad_couchdb
9e218bbd6a1f   rubinlab/mariadb:latest                                    "docker-entrypoint.s…"   17 hours ago   Up 17 hours (healthy)       3306/tcp                                               epad_mariadb
```

Looking for tips on how to get the Docker ePAD Server up and running.

**Comment by acavit** [comment]
Hi Thomas is it possible to take a look together ? A zoom call ?
Thanks

**Comment by thomasjtaylor** [comment]
Hi,

I have available time today from 2pm - 4pm ET.

Best,

Thomas Taylor
