### ISSUE TITLE
epad_couchdb required username and password since couchdb 3.0

### ISSUE THREAD

**Issue by fvdnabee** [RubinLab/epad-dist#3]
couchdb updated their latest docker images to 3.0 which now has 'Admin Party mode.' disabled. 

When running `docker-compose up`, epad_couchdb fails with a message to set 'COUCHDB_USER=admin -e COUCHDB_PASSWORD=password'

One workaround is to change the image property from 'latest' to '2.3' in the douchdb dict in `epad.yml`. Then epad_couchdb is working again.

Note that epad still fails for me due to authentication errors (even after I fillin the SSO prompt). I can't say whether they are caused by to the docker containerization as defined in this repo though. Where would be a proper place for reporting such issues? epad_lite? Auth error is below:

> epad_lite     | {"level":30,"time":1583512999975,"pid":17,"hostname":"c6c8b7364d28","reqId":12,"req":{"method":"POST","url":"/api/users","hostname":"localhost","remoteAddress":"172.18.0.7","remotePort":55146},"msg":"incoming request","v":1}
> epad_lite     | {"level":30,"time":1583512999975,"pid":17,"hostname":"c6c8b7364d28","msg":"Request needs to be authenticated, checking the authorization header","v":1}
> epad_lite     | {"level":50,"time":1583512999976,"pid":17,"hostname":"c6c8b7364d28","reqId":12,"req":{"method":"POST","url":"/api/users","hostname":"localhost","remoteAddress":"172.18.0.7","remotePort":55146},"res":{"statusCode":500},"err":{"type":"UnauthenticatedError","message":"Bearer token does not exist","stack":"UnauthenticatedError: Bearer token does not exist\n    at Object.authCheck (/home/node/app/plugins/Other.js:732:16)\n    at Object.auth (/home/node/app/plugins/Other.js:810:38)\n    at hookIterator (/home/node/app/node_modules/fastify/lib/hooks.js:124:10)\n    at next (/home/node/app/node_modules/fastify/lib/hooks.js:70:20)\n    at hookRunner (/home/node/app/node_modules/fastify/lib/hooks.js:84:3)\n    at preValidationCallback (/home/node/app/node_modules/fastify/lib/handleRequest.js:93:5)\n    at handler (/home/node/app/node_modules/fastify/lib/handleRequest.js:70:5)\n    at done (/home/node/app/node_modules/fastify/lib/contentTypeParser.js:115:7)\n    at Parser.defaultJsonParser [as fn] (/home/node/app/node_modules/fastify/lib/contentTypeParser.js:206:5)\n    at IncomingMessage.onEnd (/home/node/app/node_modules/fastify/lib/contentTypeParser.js:185:25)\n    at IncomingMessage.emit (events.js:323:22)\n    at endReadableNT (_stream_readable.js:1204:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","name":"UnauthenticatedError","data":{"message":"Bearer token does not exist"}},"msg":"Bearer token does not exist","v":1}

**Comment by emelalkim** [comment]
Hi, we'll resolve the issue as soon as possible. Unfortunately it needs changes in the codebases too so it will take some time. We suggest using version 2.3 till then

**Comment by emelalkim** [comment]
It is ok to open an auth issue here as this is most probably a configuration issue. did you use localhost as the hostname? unfortunately it doesn't work with localhost, as for each docker container localhost points to itself. you need to use either the ip or shared hostname.
